### ISSUE TITLE
[proposal] use polling only at start time, and then use docker events

### ISSUE THREAD

**Issue by docteurklein** [ahmetalpbalkan/wagl#5]
I saw in your talk @dockerCon that you often cited "huge list" polling as a problem, and that it's not really event driven.

Could you make it so the polling is only done at startup, in order to get the containers before the wagl is listnening, and then only use docker events?

it would reduce the network footprint (?) and also reduce the verbosity and repetition of the logs.

Thoughts?

**Comment by ahmetb** [comment]
@docteurklein Nice catch! Yes, we do currently poll list of all containers. It initially began as an innocent implementation decision to keep the code simple but over time I have developed some arguments around it:

First of all, I am not sure if the events are guaranteed to be delivered? For instance, if there is something wrong with the event publishing system, does the Docker engine stop creating the container if "create" event is failed to be published? The answer is no. You can take a look at `daemon/event` and `pkg/pubsub` for the details. 

More on delivery guarantee, since we keep an open connection to events source (docker-engine or in this case swarm manager), we maintain a network connection, which can go bad. I am not sure how we can detect faults such as network partitions, as in theory they look like timeout, and once the connection is restored, we need a way determining that and reloading the missing events, which can be discarded in the meanwhile from the history, or the full list of containers. 

Also how docker-engine processes the events and how Swarm manager aggregates and re-publishes the events from individual engines is probably different than the engine and I bet there are even lower guarantees around it. For these three reasons, I tend to think events are just informational.

I should also mention that, the events do not return any info other than container IDs, so you will be making requests to the docker-engine, and in case of rapid-creation of containers (something that can easily happen in a cluster environment, 200 containers can come up pretty fast) docker-engine (and probably swarm) will roll-up events after a number like 100, if you miss processing events in that timeframe, they're gone. Also, you're still making "Get Container" requests for each of these events, so you're putting a burden on the swarm or docker-engine even more.

Also the event-based system scalability concerns such as when a lot of containers are created/deleted in a short timeframe as I mentioned above, this will put a heavy compute/networking burden on the DNS server (which would cause DNS queries to slow down, and thus the actual applications relying on DNS will be impacted). This is a case where a control-plane load would be affecting the actual workloads, which I bet something quite undesirable for any user.

The polling model has a predictable load: one linearly increasing execution time and a burden on the Docker Engine (in this case Swarm engine) as number of the containers increase, as we both know. I'd like to explore how Swarm keeps up to date with the individual engines (does it use some combination of events and polling perhaps?).

AFAIK docker-engine serves this "List Containers" request from memory and a docker engine usually does not run a lot of containers (imagine of the common use case, it's probably 5-10), and I imagine Swarm keeps the containers' info in-memory as well, so I am assuming the "List Containers" requests are not really expensive, and has a predictable (and configurable) load on the engine/swarm.

That said, not having events makes the system work with delays, such as discovery of containers are slow and taking the stopped containers out of rotation is also slow. DNS can somewhat tolerate that, and applications must have retry policies for such scenarios anyway regardless of them using DNS service discovery, because things go down all the time. 

Logging verbosity is not much of a concern, you can tune it down.

The extra network traffic introduced by wagl queries should not be also very high, as suggested method to deploy wagl is to place it right next to swarm manager –however manager can be a follower that's proxying the request to the one that's leader, but then these are some machines probably in the same virtual LAN, often in the same cluster or rack of the same DC.

I should also mention the implementation complexity of an event-based system would bring to the codebase is not a small thing. I really doubt the event-based model, maybe a combination of both is really what we need.

As I mentioned, systems such as interlock/registrator listen for events, but get the full list of containers anyway. However that means that in case of events got lost or dropped, you will not be discovering the added service (or taking the down service out of rotation) until another container event occurs, which I think is a worse thing than the polling.

So as you see if I start to think out loud, I can get very chatty and boring easily. I can count more downsides to the polling model, I am well aware of it is not awesome either, however the bottom line is it seems like it does just fine and has less downsides than the event model. Nobody deploys 1000-node swarm clusters yet, nor they should use wagl as it is nowhere close to an enterprise-grade software. If this case changes and we need to build something that is proven that it needs improvement, we shall re-evaluate the event-based model.

Sorry for the long answer. :-)

**Comment by docteurklein** [comment]
thanks, your answer makes a lot of sense.
Didn't even think of delivery guarantee or n+1 requests.

Closing.

**Comment by ahmetb** [comment]
There's even a lot more to this problem than these and it requires a clear understanding of event publishing and processing model of Swarm and thus docker-engine. If you look at mesos-dns, it also chooses mesos master as the event source and it also polls for the truth (`/state.json` endpoint) and gets the list of all containers. Apparently even at mesos scale, they were able to get away with it, maybe it's just fine after all. :-) But I'm pretty sure as you said, these poll based systems will be problematic at high scales, we just don't know if other things will be broken until the dns server or the HTTP requests to master will be broken. :-)
