### ISSUE TITLE
How do I get wagl to work with my swarm

### ISSUE THREAD

**Issue by funkytaco** [ahmetalpbalkan/wagl#7]
I can see my TLS .pem files like this in `/etc/docker`:

```
docker run --rm --volumes-from swarm-data ahmet/wagl ls /etc/docker`
ca.pem
server-cert.pem
server-key.pem
```

  (being mounted from the swarm data)

But this doesn't seem to work.

```
docker run -d --restart=always --name=dns \
 -p 53:53/udp \
    --link "$SWARM_HASH":swarm \
    ahmet/wagl wagl --volumes-from swarm-data \
    --swarm-cert-path /etc/docker \
    --swarm tcp://swarm:2376
```

For some reason wagl docker logs show the following, and it keeps restarting:

```
Incorrect Usage.

NAME:
   wagl - DNS service discovery for Docker Swarm clusters

[ snipped....]

```

**Comment by ahmetb** [comment]
Hello @funkytaco. The readme file has a 5-Minute Tutorial curated with docker-machine and docker-swarm. I suggest following that once. It also shows handling of certs too. But I think you got that part right.

In this case, your problem is, `--volumes-from` argument appears after `ahmet/wagl wagl ...`. It's an argument to `docker`, not `ahmet/wagl` image. Therefore it should appear before the image name, `ahmet/wagl`. I hope this helps.

**Comment by funkytaco** [comment]
I did watch the video but Rackspace Carina (Docker Swarm open beta) uses AppArmor so I can't use `-v` to link to the PEM files. I got it working like this:

docker run --volumes-from swarm-data --name=ssl-data -d ahmet/wagl sh -c "cp /etc/docker/server-cert.pem /etc/docker/cert.pem && cp /etc/docker/server-key.pem /etc/docker/key.pem"

WAGL_CONTAINER=`docker run -d --restart=always --name=dns \
    -p 53:53/udp \

```
--link "$SWARM_HASH":swarm \

--volumes-from ssl-data \

ahmet/wagl wagl \

--domain my.domain \

--swarm-cert-path /etc/docker \

--swarm tcp://swarm:2376
```

`

So it looks like it's working. I'm experiencing a different issue, so I'm going to close this.
